version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  app:
    build: ./frontend/footprint-calculator
    environment:
      - VIRTUAL_HOST=co2vid19.ch