# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: forever stopall
    - run: cd backend/answers-logger && npm ci
    - run: cd backend/answers-logger && npm run build
    - run: mv backend/answers-logger/build/app.js ~/backend-prod/build/
    - run: rm -dr backend/answers-logger/node_modules
    - run: mv backend/answers-logger/node_modules ~/backend-prod
    - run: forever start ~/backend-prod/build/app.js
      env:
        CI: true
